GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/6

###
GET http://localhost:3001/api/nonexistent


###

POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "Progress with the tutorials.",
    "important": false
}

###

DELETE http://localhost:3001/api/notes/1