GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/84311

###

DELETE http://localhost:3001/api/persons/10

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Someone else",
    "number": "1234-242"
}