POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "jack",
    "name": "Jack Rabbit",
    "password": "rabbit!"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "someone",
    "name": "Some One",
    "password": "somepassword"
}

### Attempt to create an invalid user (password is missing)

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "testuser-2",
    "name": "Test User 2"
}

### Attempt to create an invalid user (password is too short)

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "testuser-3",
    "name": "Test User 3",
    "password": "qq"
}

### Get all the users

GET http://localhost:3001/api/users

### Get a specific user

GET http://localhost:3001/api/users/6924319f5ed8168766f25ffa

### Delete a specific user (no cascade: does not delete the blogs created by the user) 
DELETE http://localhost:3001/api/users/69242b39152268fca9fc94db
